# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: fernando21
# "service" is the name of this project. This will also be added to your AWS resource names.
service: challenge-serverless

provider:
  name: aws
  runtime: nodejs20.x
  stage: dev
  region: us-east-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:GetItem"
        - "dynamodb:PutItem"
        - "dynamodb:UpdateItem"
        - "dynamodb:DeleteItem"
        - "dynamodb:Scan"
      Resource: 
        - "arn:aws:dynamodb:us-east-1:794038249206:table/Persona"

functions:
  getPersonas:
    handler: src/handlers/getPersonas.handler
    events:
      - httpApi:
          path: /personas
          method: get
  postPersonas:
    handler: src/handlers/postPersonas.handler
    events:
      - httpApi:
          path: /personas
          method: post

package:
  include:
    - node_modules/**
  exclude:
    - ./**/.git/**
    - ./**/.gitignore
    - ./**/.env*
    - ./**/.serverless/**
    - ./**/.terraform/**