service: challenge-api

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:PutItem"
        - "dynamodb:Scan"
        - "dynamodb:GetItem"
      Resource:
        - "arn:aws:dynamodb:us-east-1:*:table/Persona"

functions:
  getPersona:
    handler: src/handlers/getPersona.handler
    events:
      - http:
          path: persona
          method: get
  postPersona:
    handler: src/handlers/postPersona.handler
    events:
      - http:
          path: persona
          method: post